import { test, expect } from '@playwright/test'
import { registrationData } from './registration'

for (const width of [320, 390, 768, 1280]) test(`KH-019 focus lifecycle ${width}`, async ({ page }, info) => {
  await page.setViewportSize({ width, height: 844 })
  if (width === 320) await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/inventory')
  const trigger = page.getByRole('button', { name: 'Añadir', exact: true })
  for (const close of ['Escape', 'X', 'backdrop']) {
    await trigger.focus(); await trigger.press('Enter')
    const dialog = page.getByRole('dialog')
    await expect(dialog).toHaveAttribute('aria-modal', 'true')
    await expect(dialog.getByRole('searchbox')).toBeFocused()
    await trigger.focus()
    expect(await dialog.evaluate(el => el.contains(document.activeElement))).toBe(true)
    expect(await dialog.evaluate(el => el.scrollWidth <= el.clientWidth)).toBe(true)
    await page.screenshot({ path: `/tmp/kh019-sheet-${width}.png`, animations: 'disabled' })
    const first = dialog.getByRole('button').first()
    const last = dialog.getByRole('button').last()
    await first.focus(); await page.keyboard.press('Shift+Tab'); await expect(last).toBeFocused()
    await page.keyboard.press('Tab'); await expect(first).toBeFocused()
    if (close === 'Escape') await page.keyboard.press('Escape')
    else if (close === 'X') await dialog.getByRole('button', { name: 'Cerrar' }).press('Space')
    else await dialog.click({ position: { x: 1, y: 1 } })
    await expect(dialog).toHaveCount(0)
    await expect(trigger).toBeFocused()
  }
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: `/tmp/kh019-focus-${width}.png` })
  // Account-scoped real save and deletion: existing trigger, then disconnected trigger.
  const context = await page.context().browser()!.newContext({ viewport: { width, height: 844 }, baseURL: 'http://127.0.0.1:3100' })
  const isolated = await context.newPage()
  if (width === 320) await isolated.emulateMedia({ reducedMotion: 'reduce' })
  expect((await isolated.request.post('/api/auth/register', { data: registrationData('focus'), headers: { 'X-Forwarded-For': info.testId } })).status()).toBe(201)
  const product = await (await isolated.request.post('/api/products', { data: { name: `Focus ${width}`, category: 'other' } })).json()
  await isolated.request.post('/api/pantry', { data: { productId: product.id, quantity: 3, unit: 'kg' } })
  await isolated.goto('/inventory')
  const row = isolated.getByRole('button').filter({ hasText: `Focus ${width}` })
  await row.focus(); await row.press('Space')
  await isolated.getByRole('spinbutton', { name: 'Cantidad', exact: true }).fill('4')
  await isolated.getByRole('button', { name: 'Guardar cambios' }).press('Enter')
  await expect(row).toBeFocused()
  await row.press('Enter')
  await isolated.getByRole('button', { name: 'Quitar de la despensa' }).press('Enter')
  await expect(row).toHaveCount(0)
  await expect(isolated.getByRole('button', { name: 'Añadir', exact: true })).toBeFocused()
  await context.close()
})
