import { test, expect } from '@playwright/test'
import { registrationData } from './registration'
test.use({storageState:{cookies:[],origins:[]}})
for(const width of [320,390,768,1280]) for(const reducedMotion of [false,true]) test(`KH-016 repeated add, edit and concurrent undo at ${width} (${reducedMotion?'reduced':'normal'} motion)`,async({page,context},info)=>{
  expect((await page.request.post('/api/auth/register',{data:registrationData('readd'),headers:{'X-Forwarded-For':info.testId}})).status()).toBe(201)
  const name=`Producto largo para comprobar reañadir sin cambiar cantidades ${width}`
  const product=await(await page.request.post('/api/products',{data:{name,category:'other'}})).json()
  const created=await(await page.request.post('/api/pantry',{data:{productId:product.id,quantity:3,unit:'kg'}})).json()
  expect(created.outcome).toBe('created')
  await page.setViewportSize({width,height:844}); await page.emulateMedia({reducedMotion:reducedMotion?'reduce':'no-preference'})
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message))
  await page.goto('/inventory')
  const row=page.getByRole('button').filter({hasText:name})
  await expect(row).toContainText('3 kg')
  const add=page.getByRole('button',{name:'Añadir',exact:true})
  await add.focus();await add.press('Enter')
  let dialog=page.getByRole('dialog')
  await dialog.getByRole('button',{name:'Manual',exact:true}).click()
  await dialog.getByRole('textbox',{name:'Producto',exact:true}).fill(name)
  await dialog.getByRole('spinbutton',{name:'Cantidad',exact:true}).fill('5')
  await dialog.locator('select').first().selectOption('kg')
  await dialog.getByRole('button',{name:'Añadir',exact:true}).press('Enter')
  await expect(dialog.getByRole('status')).toContainText('Ya está en tu despensa')
  await expect(dialog.getByRole('status')).not.toContainText('añadido')
  await expect(row).toContainText('3 kg')
  const fits=async()=>expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
  await fits();await page.screenshot({path:`/tmp/kh016-existing-${width}-${reducedMotion?'reduced':'normal'}.png`,animations:'disabled'})
  const edit=dialog.getByRole('button',{name:'Editar cantidad',exact:true})
  await edit.focus();await edit.press('Space')
  dialog=page.getByRole('dialog')
  await expect(dialog.getByRole('spinbutton',{name:'Cantidad',exact:true})).toHaveValue('3')
  await dialog.getByRole('spinbutton',{name:'Cantidad',exact:true}).fill('5')
  await dialog.getByRole('button',{name:'Guardar cambios',exact:true}).press('Enter')
  await expect(dialog).toHaveCount(0);await expect(row).toContainText('5 kg')
  await row.focus();await row.press('Space');await page.getByRole('button',{name:'Quitar de la despensa'}).press('Enter')
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(row).toHaveCount(0)
  const response=await context.request.post('/api/pantry',{data:{productId:product.id,quantity:7,unit:'kg'}})
  expect((await response.json()).outcome).toBe('created')
  const undo=page.getByRole('button',{name:'Deshacer',exact:true})
  await expect(undo).toBeVisible()
  await undo.focus();await expect(undo).toBeFocused()
  const restored=page.waitForRequest(request=>request.url().endsWith('/api/pantry')&&request.method()==='POST')
  await page.keyboard.press('Space')
  const restoreRequest=await restored
  expect(restoreRequest.postDataJSON()).toEqual({productId:product.id,quantity:5,unit:'kg'})
  await expect(page.getByRole('status')).toContainText('Ya está en tu despensa')
  await expect(row).toContainText('7 kg')
  const stock=await(await page.request.get('/api/pantry')).json()
  expect(stock.filter((p:{productId:string})=>p.productId===product.id)).toHaveLength(1)
  expect(stock.find((p:{productId:string})=>p.productId===product.id)).toMatchObject({quantity:7,unit:'kg'})
  await fits();await page.screenshot({path:`/tmp/kh016-undo-${width}-${reducedMotion?'reduced':'normal'}.png`,animations:'disabled'})
  await page.getByRole('button',{name:'Editar',exact:true}).press('Enter')
  await expect(page.getByRole('dialog').getByRole('spinbutton',{name:'Cantidad',exact:true})).toHaveValue('7')
  await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).toHaveCount(0)
  await page.reload();await expect(row).toContainText('7 kg')
  expect(errors).toEqual([])
})
