import { test, expect } from '@playwright/test'
import Database from 'better-sqlite3'
import { resolveSqlitePath } from '../src/lib/sqliteUrl'
import { registrationData } from './registration'

test.use({ storageState: { cookies: [], origins: [] } })
for (const width of [320,390,768,1280]) {
  test(`KH-005 recipe -> need -> package -> pantry, legacy and keyboard at ${width}`, async ({ page }, info) => {
    const registration = registrationData()
    expect((await page.request.post('/api/auth/register',{ data: registration, headers: { 'X-Forwarded-For': `kh005-${info.testId}` } })).status()).toBe(201)
    const dbPath = resolveSqlitePath(process.env.DATABASE_URL, true)
    if (dbPath.endsWith('/dev.db')) throw new Error('Refusing original DB')
    const sql = new Database(dbPath)
    const recipeId = `kh005-${info.testId}-${Date.now()}`
    const name = `Pechuga de pollo para la receta ${width}`
    try {
      sql.prepare('INSERT INTO Recipe(id,title,description,mealTypes,prepTimeMinutes,difficulty,ketoLevel,steps,updatedAt) VALUES(?,?,?,?,?,?,?,?,?)').run(recipeId, name, 'Fixture quantity flow', '["lunch"]', 30, 'easy','strict','[]',Date.now())
      sql.prepare('INSERT INTO RecipeIngredient(id,recipeId,name,quantity) VALUES(?,?,?,?)').run(recipeId+'-ingredient',recipeId,name,'300 g')
      sql.prepare("INSERT INTO ShoppingListItem(id,name,quantity,userId,updatedAt) VALUES(?,?,?,(SELECT id FROM User WHERE email=?),?)").run(recipeId+'-legacy','Legacy sin cantidad fiable','1',registration.email,Date.now())
    } finally { sql.close() }
    const errors: string[] = []
    page.on('pageerror',e => errors.push(e.message))
    await page.setViewportSize({ width, height: 844 })
    if (width === 320) await page.emulateMedia({ reducedMotion: 'reduce' })
    await page.goto(`/recipes/${recipeId}`)
    await page.getByRole('button',{ name: /Añadir.*lista/ }).click()
    const generated = await (await page.request.get('/api/shopping-list')).json()
    const need = generated.find((i: {name:string}) => i.name === name)
    expect(need).toMatchObject({ requiredQuantity: 300, requiredUnit: 'g', originalIngredientText: '300 g', purchaseQuantity: null })
    expect((await (await page.request.post(`/api/recipes/${recipeId}/add-to-shopping-list`)).json()).added).toBe(0)
    const product = await (await page.request.post('/api/products',{ data: { name: `Bandeja comercial ${width}`, category: 'meat', packageQuantity: 500, packageUnit: 'g', unitPrice: 5 } })).json()
    expect((await page.request.patch(`/api/shopping-list/${need.id}/quantity`, { data: { productId: product.id, purchaseQuantity: 1 } })).status()).toBe(200)
    await page.goto('/shopping-list')
    await expect(page).toHaveURL(/\/shopping-list/)
    await expect(page.getByRole('heading',{name:'Lista de compra'})).toBeVisible()
    const row = page.getByRole('listitem').filter({ hasText: name })
    await expect(row.getByText('Necesidad: 300 g',{exact:true})).toBeVisible()
    await expect(row.getByText('Envase: 500 g',{exact:true})).toBeVisible()
    await expect(row.getByText('Compra: 1 paquete',{exact:true})).toBeVisible()
    const legacy = page.getByRole('listitem').filter({hasText:'Legacy sin cantidad fiable'})
    await expect(legacy.getByText('Cantidad necesaria no especificada')).toBeVisible()
    await expect(legacy.getByText('1',{exact:true})).toHaveCount(0)
    await legacy.getByRole('button',{name:'Quitar Legacy sin cantidad fiable de la lista'}).click()
    await expect(legacy).toHaveCount(0)
    await page.getByRole('button',{name:'Deshacer',exact:true}).click()
    await expect(legacy).toBeVisible()
    const restored = (await (await page.request.get('/api/shopping-list')).json()).find((i: {name:string}) => i.name === 'Legacy sin cantidad fiable')
    expect(restored).toMatchObject({ quantity:'1', purchaseQuantity:null, sourceType:'legacy' })
    await expect(legacy.getByText('1',{exact:true})).toHaveCount(0)
    const fits = async () => expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await fits()
    await page.screenshot({ path: `/tmp/kh005-shopping-${width}.png`, fullPage: true, animations: 'disabled' })
    const buy = row.getByRole('button',{name:`Marcar ${name} como comprado`})
    await buy.focus(); await page.keyboard.press('Tab')
    await expect(row.getByRole('button',{name:`Quitar ${name} de la lista`})).toBeFocused()
    await page.keyboard.press('Shift+Tab'); await expect(buy).toBeFocused()
    await page.keyboard.press('Enter')
    const stock = async () => (await (await page.request.get('/api/pantry')).json()).find((p: {productId:string}) => p.productId === product.id)
    await expect.poll(async () => (await stock())?.quantity).toBe(500)
    await page.reload()
    await expect(page.getByRole('button',{name:`Devolver ${name} a la lista`})).toBeVisible()
    await page.goto('/inventory')
    const pantryRow = page.getByRole('button').filter({hasText:`Bandeja comercial ${width}`})
    await expect(pantryRow).toContainText('500 g')
    await pantryRow.focus(); await page.keyboard.press('Space')
    const dialog = page.getByRole('dialog')
    await expect(dialog).toBeVisible(); await fits()
    await page.screenshot({ path: `/tmp/kh005-pantry-dialog-${width}.png`, animations:'disabled' })
    await page.keyboard.press('Escape'); await expect(pantryRow).toBeFocused()
    await page.goto('/shopping-list')
    const undo = page.getByRole('button',{name:`Devolver ${name} a la lista`})
    await undo.focus(); await undo.press('Space')
    await expect.poll(stock).toBe(undefined)
    await page.reload(); await expect(buy).toBeVisible(); await fits()
    // Manual dialog distinguishes package count; existing autofocus/trigger restoration belongs to KH-019.
    const add = page.locator('main header').getByRole('button',{name:'Añadir',exact:true})
    await add.focus(); await add.press('Enter')
    await page.getByRole('button',{name:'Manual',exact:true}).click()
    await expect(dialog.getByLabel('Cantidad de paquetes')).toBeVisible(); await fits()
    await dialog.getByLabel('Producto',{exact:true}).focus(); await page.keyboard.press('Tab')
    await expect(dialog.getByLabel('Cantidad de paquetes')).toBeFocused()
    await page.keyboard.press('Shift+Tab'); await expect(dialog.getByLabel('Producto',{exact:true})).toBeFocused()
    await page.screenshot({ path: `/tmp/kh005-add-dialog-${width}.png`, animations:'disabled' })
    await page.keyboard.press('Escape'); await expect(dialog).toHaveCount(0)
    expect(errors).toEqual([])
  })
}
test('KH-005 normalized count unit remains visible and editable in pantry', async ({ page }, info) => {
  expect((await page.request.post('/api/auth/register',{ data: registrationData(), headers: { 'X-Forwarded-For': `kh005-unit-${info.testId}` } })).status()).toBe(201)
  const product = await (await page.request.post('/api/products',{ data: { name: 'Envase de seis huevos', category: 'eggs', packageQuantity: 6, packageUnit: 'unidades' } })).json()
  const item = await (await page.request.post('/api/shopping-list',{ data: { name: product.name, productId: product.id, quantity: 1 } })).json()
  expect((await page.request.patch(`/api/shopping-list/${item.id}/check`)).status()).toBe(200)
  await page.goto('/inventory')
  const row = page.getByRole('button').filter({hasText:product.name})
  await expect(row).toContainText('6 unidad')
  await row.click()
  const dialog = page.getByRole('dialog')
  await expect(dialog.getByLabel('Unidad')).toHaveValue('unidad')
  await dialog.getByLabel('Cantidad',{exact:true}).fill('4')
  await dialog.getByRole('button',{name:'Guardar cambios'}).click()
  await expect(row).toContainText('4 unidad')
  const stock = await (await page.request.get('/api/pantry')).json()
  expect(stock[0]).toMatchObject({ quantity: 4, unit: 'unidad' })
})
for (const width of [320,390,768,1280]) {
  test(`KH-005 catalog never infers packages from a culinary or legacy counter at ${width}`, async ({ page }, info) => {
    expect((await page.request.post('/api/auth/register',{ data: registrationData(), headers: { 'X-Forwarded-For': `kh005-catalog-${info.testId}` } })).status()).toBe(201)
    const product = { id: 'kh005-catalog', mercadonaId: 'kh005-catalog', name: 'Pollo de catálogo', category: 'meat', ketoScore:5, unitPrice: 5, imageUrl: null, brand: 'Mercadona', classification: { score: 5, label: 'Estimación por categoría', source: 'category_estimate', evidence: 'category_name' } }
    let items: Array<{ id: string; checked: boolean; sourceType: string; quantity: string | null; requiredQuantity: number | null; originalIngredientText: string | null; purchaseQuantity: number | null; product: typeof product }> = [{ id: 'need', checked: false, sourceType: 'recipe', quantity: null, requiredQuantity: 300, originalIngredientText: '300 g', purchaseQuantity: null, product }, { id: 'legacy', checked: false, sourceType: 'legacy', quantity: '1', requiredQuantity: null, originalIngredientText: null, purchaseQuantity: null, product }]
    await page.route('**/api/shopping-list', route => route.fulfill({ json: items }))
    await page.route('**/api/mercadona/**', route => route.fulfill({ json: route.request().url().includes('/product/') ? product : { products: [product] } }))
    await page.setViewportSize({ width, height:844 })
    await page.goto('/explore')
    await expect(page.getByRole('button',{name:'Añadir Pollo de catálogo a la lista'})).toBeVisible()
    await expect(page.getByRole('button',{name:'Quitar un paquete de Pollo de catálogo'})).toHaveCount(0)
    await expect(page.getByRole('link',{name:/Ver lista/})).not.toContainText('€')
    const trigger = page.locator('main ul li').first().getByRole('button').filter({hasText:'€'})
    await trigger.focus(); await trigger.press('Enter')
    const dialog = page.getByRole('dialog')
    await expect(dialog.getByText('Compra por paquetes',{exact:true})).toBeVisible()
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await page.screenshot({path:`/tmp/kh005-catalog-dialog-${width}.png`,animations:'disabled'})
    await page.keyboard.press('Escape'); await expect(trigger).toBeFocused()
    items = [...items, { id:'manual', checked:false, sourceType:'manual', quantity:'2', requiredQuantity:null, originalIngredientText:null, purchaseQuantity:2, product }]
    await page.reload()
    await expect(page.getByRole('button',{name:'Quitar un paquete de Pollo de catálogo'})).toBeVisible()
    await expect(page.getByRole('link',{name:/Ver lista/})).toContainText('10,00 €')
  })
}
