import { test, expect } from '@playwright/test'
import Database from 'better-sqlite3'
import { resolveSqlitePath } from '../src/lib/sqliteUrl'
import { registrationData } from './registration'
test.use({storageState:{cookies:[],origins:[]}})
for(const width of [320,390,768,1280]) test(`KH-027 aggregated shopping, retry, keyboard and partial plan at ${width}`,async({page},info)=>{
  const registration=registrationData('weekly-shopping')
  expect((await page.request.post('/api/auth/register',{data:registration,headers:{'X-Forwarded-For':info.testId}})).status()).toBe(201)
  const generated=await page.request.post('/api/weekly-plan/generate')
  expect(generated.status()).toBe(200)
  const plan=await generated.json()
  const sql=new Database(resolveSqlitePath(process.env.DATABASE_URL,true))
  const id=`kh027-${width}-${Date.now()}`
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message))
  const consoleErrors:string[]=[];page.on('console',m=>{if(m.type()==='error'&&!m.text().includes('Failed to load resource'))consoleErrors.push(m.text())})
  try{
    const {id:userId}=sql.prepare('SELECT id FROM User WHERE email=?').get(registration.email) as {id:string}
    sql.transaction(()=>{
      const insert=sql.prepare('INSERT INTO Recipe(id,title,description,mealTypes,prepTimeMinutes,difficulty,ketoLevel,steps,imageUrl,updatedAt) VALUES(?,?,?,?,?,?,?,?,?,?)')
      insert.run(id,`Pollo ${id}`,'','["lunch"]',30,'easy','strict','[]','/icon.svg',Date.now())
      insert.run(`${id}-empty`,`Base ${id}`,'','["breakfast","lunch","snack","dinner"]',30,'easy','strict','[]','/icon.svg',Date.now())
      sql.prepare('INSERT INTO Product(id,name,source,category,updatedAt) VALUES(?,?,?,?,?)').run(id,`Pollo ${id}`,'mercadona','meat',Date.now())
      sql.prepare('INSERT INTO PantryItem(id,userId,productId,quantity,unit,updatedAt) VALUES(?,?,?,?,?,?)').run(id,userId,id,500,'g',Date.now())
      sql.prepare('INSERT INTO RecipeIngredient(id,recipeId,name,quantity,productId) VALUES(?,?,?,?,?)').run(id,id,`Pollo ${id}`,'300 g',id)
      sql.prepare('INSERT INTO RecipeIngredient(id,recipeId,name,quantity) VALUES(?,?,?,?)').run(`${id}-unknown`,id,`Especias ${id}`,'al gusto')
      sql.prepare('UPDATE WeeklyMeal SET recipeId=? WHERE planId=?').run(`${id}-empty`,plan.id)
      sql.prepare("UPDATE WeeklyMeal SET recipeId=? WHERE planId=? AND dayOfWeek IN (0,2) AND mealType='lunch'").run(id,plan.id)
      sql.prepare('INSERT INTO ShoppingListItem(id,userId,name,sourceType,purchaseQuantity,updatedAt) VALUES(?,?,?,?,?,?)').run(id,userId,`Manual ${id}`,'manual',2,Date.now())
    })()
    await page.setViewportSize({width,height:900})
    if(width===320)await page.emulateMedia({reducedMotion:'reduce'})
    await page.goto('/weekly-plan')
    await expect(page.getByRole('heading',{name:'Plan semanal'})).toBeVisible()
    expect(await page.title()).toBeTruthy()
    const button=page.getByRole('button',{name:'Preparar compra de esta semana',exact:true})
    await expect(button).toBeVisible()
    await button.focus();await expect(button).toBeFocused()
    expect(await button.evaluate(el=>getComputedStyle(el).outlineStyle!=='none'||getComputedStyle(el).boxShadow!=='none')).toBe(true)
    await page.screenshot({path:`/tmp/kh027-idle-${width}.png`,animations:'disabled'})
    let requests=0;let recipeRequests=0
    page.on('request',r=>{if(r.url().includes('/api/weekly-plan/shopping-list'))requests++;if(r.url().includes('/add-to-shopping-list'))recipeRequests++})
    let release!:()=>void
    const gate=new Promise<void>(resolve=>{release=resolve})
    await page.route('**/api/weekly-plan/shopping-list',async route=>{await gate;await route.continue()})
    await button.press('Enter')
    await expect(page.getByRole('button',{name:'Preparando compra…'})).toBeDisabled()
    await page.getByRole('button',{name:'Preparando compra…'}).dispatchEvent('click')
    await expect(page.getByRole('status',{name:'Preparación de compra semanal'})).toContainText('Calculando necesidades')
    release()
    await expect(page.getByRole('status',{name:'Preparación de compra semanal'})).toContainText('Compra preparada: 3 necesidades pendientes')
    await expect(page.getByRole('status',{name:'Preparación de compra semanal'})).toContainText('2 cantidades no verificadas')
    expect(requests).toBe(1);expect(recipeRequests).toBe(0)
    let before=await(await page.request.get('/api/shopping-list')).json()
    expect(before.filter((r:{sourceType:string})=>r.sourceType==='weekly-plan')).toHaveLength(3)
    expect(before.find((r:{name:string})=>r.name===`Pollo ${id}`)).toMatchObject({requiredQuantity:100,requiredUnit:'g'})
    await button.press('Space')
    await expect(page.getByRole('status',{name:'Preparación de compra semanal'})).toContainText('0 nuevas, 0 actualizadas, 3 sin cambios')
    expect(requests).toBe(2)
    expect(await(await page.request.get('/api/shopping-list')).json()).toEqual(before)
    expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
    await page.screenshot({path:`/tmp/kh027-success-${width}.png`,animations:'disabled'})
    await page.getByRole('link',{name:'Ver lista de compra'}).click()
    await expect(page).toHaveURL(/\/shopping-list$/)
    await expect(page.getByText('Necesidad: 100 g',{exact:true})).toBeVisible()
    await expect(page.getByText(`Manual ${id}`,{exact:true})).toBeVisible()
    await page.reload();await expect(page.getByText('Necesidad: 100 g',{exact:true})).toBeVisible()
    await page.getByRole('button',{name:`Quitar Pollo ${id} de la lista`,exact:true}).click()
    await page.getByRole('button',{name:'Deshacer',exact:true}).click()
    await expect(page.getByText('Necesidad: 100 g',{exact:true})).toBeVisible()
    before=await(await page.request.get('/api/shopping-list')).json()
    expect(before.filter((r:{sourceType:string})=>r.sourceType==='weekly-plan')).toHaveLength(3)
    expect(before.find((r:{name:string})=>r.name===`Pollo ${id}`).sourceContributions).toContain('slotId')
    expect(recipeRequests).toBe(0)
    // A failed operation gives recoverable feedback and no premature success.
    await page.goto('/weekly-plan')
    await page.unroute('**/api/weekly-plan/shopping-list')
    await page.route('**/api/weekly-plan/shopping-list',route=>route.fulfill({status:500,contentType:'application/json',body:JSON.stringify({error:'Fallo temporal de prueba'})}))
    await button.click();await expect(page.locator('main').getByRole('alert')).toContainText('Fallo temporal de prueba')
    await expect(page.getByRole('status',{name:'Preparación de compra semanal'})).not.toContainText('Compra preparada')
    await expect(button).toBeEnabled()
    await page.unroute('**/api/weekly-plan/shopping-list')
    sql.prepare('DELETE FROM WeeklyMeal WHERE planId=? AND dayOfWeek=6').run(plan.id)
    await page.reload()
    await expect(button).toBeDisabled()
    await expect(page.getByText('Plan incompleto: genera las 28 comidas para preparar la compra semanal.')).toBeVisible()
    expect((await page.request.post('/api/weekly-plan/shopping-list',{data:{planId:plan.id}})).status()).toBe(422)
    expect(await(await page.request.get('/api/shopping-list')).json()).toEqual(before)
    expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
    await page.screenshot({path:`/tmp/kh027-partial-${width}.png`,animations:'disabled'})
    expect(errors).toEqual([]);expect(consoleErrors).toEqual([])
  }finally{
    sql.transaction(()=>{
      sql.prepare('DELETE FROM WeeklyMeal WHERE recipeId IN (?,?)').run(id,`${id}-empty`)
      sql.prepare('DELETE FROM RecipeIngredient WHERE recipeId=?').run(id)
      sql.prepare('DELETE FROM Recipe WHERE id IN (?,?)').run(id,`${id}-empty`)
    })();sql.close()
  }
})


test('KH-027 UI swap and regeneration synchronize sources while a manual item survives',async({page},info)=>{
  expect((await page.request.post('/api/auth/register',{data:registrationData('weekly-swap'),headers:{'X-Forwarded-For':info.testId}})).status()).toBe(201)
  const manual=await(await page.request.post('/api/shopping-list',{data:{name:'Manual milk outside plan',quantity:2}})).json()
  expect((await page.request.post('/api/weekly-plan/generate')).status()).toBe(200)
  await page.goto('/weekly-plan')
  const prepare=page.getByRole('button',{name:'Preparar compra de esta semana',exact:true})
  const status=page.getByRole('status',{name:'Preparación de compra semanal'})
  await prepare.click();await expect(status).toContainText('Compra preparada')
  const oldPlan=await(await page.request.get('/api/weekly-plan')).json()
  const slot=oldPlan.meals.find((m:{dayOfWeek:number;mealType:string})=>m.dayOfWeek===0&&m.mealType==='lunch')
  await page.getByRole('button',{name:'Cambiar comida del lunes',exact:true}).click()
  const choice=page.getByRole('dialog').getByRole('button').filter({hasText:'min'}).first()
  await expect(choice).toBeVisible();await choice.click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(status).not.toContainText('Compra preparada')
  await expect.poll(async()=> (await(await page.request.get('/api/weekly-plan')).json()).meals.find((m:{id:string})=>m.id===slot.id).recipeId).not.toBe(slot.recipeId)
  await prepare.click();await expect(status).toContainText('Compra preparada')
  const swapped=await(await page.request.get('/api/weekly-plan')).json()
  let list=await(await page.request.get('/api/shopping-list')).json()
  const sources=list.filter((r:{sourceType:string})=>r.sourceType==='weekly-plan').flatMap((r:{sourceContributions:string})=>JSON.parse(r.sourceContributions).sources)
  expect(sources.filter((s:{slotId:string;recipeId:string})=>s.slotId===slot.id).every((s:{recipeId:string})=>s.recipeId===swapped.meals.find((m:{id:string})=>m.id===slot.id).recipeId)).toBe(true)
  expect(list.find((r:{id:string})=>r.id===manual.id)).toEqual(manual)
  await page.getByRole('button',{name:'Regenerar',exact:true}).click()
  await page.getByRole('dialog').getByRole('button',{name:'Regenerar',exact:true}).click()
  await expect.poll(async()=>(await(await page.request.get('/api/weekly-plan')).json()).id).not.toBe(oldPlan.id)
  await expect(prepare).toBeEnabled();await prepare.click();await expect(status).toContainText('Compra preparada')
  const current=await(await page.request.get('/api/weekly-plan')).json()
  list=await(await page.request.get('/api/shopping-list')).json()
  expect(list.filter((r:{sourceType:string})=>r.sourceType==='weekly-plan').every((r:{sourceContributions:string})=>JSON.parse(r.sourceContributions).planId===current.id)).toBe(true)
  expect(list.find((r:{id:string})=>r.id===manual.id)).toEqual(manual)
})
